/**
 * \file main.c
 * \brief Main function definition for Cpu: SCR.
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

/* TODO: To be updated with the iLLD driver code */

#include "IfxScr_reg.h"
#include "Cpu/Std/IfxScrCpuIrq.h"
#include "Scu/Std/IfxScrScu.h"
#include "Port/Std/IfxScrPort.h"
#include "Rtc/Std/IfxScrRtc.h"

#define PORT0 IfxScrPort_Index_00
#define PIN1  IfxScrPort_PinIndex_1
#define __INTNO(nr) ((8*nr)+3)

volatile __xdata unsigned char rtc_flag    __at(0x700C);

void __interrupt(__INTNO(13)) rtc_interrupt(void)
{
	IfxScrPort_togglePinState(PORT0, PIN1); //Toggle port P33.0
	rtc_flag++;
}

void main(void)
{
    uint8 i = 0;
    IfxScrRtc_Config Rtc_Config;	//RTC

    IfxScrCpuIrq_sendMessageToTricore(0xEE);
    //disable bit protection scheme(PASSWD.MODE = 00b)
    IfxScrScu_disableBitProtectionScheme();

    //Enable the global Interrupt
    IfxScrCpuIrq_enableGlobalInterrupt();

    while(IfxScrCpuIrq_readMessageFromTricore() != 0xAA);
    IfxScrCpuIrq_sendMessageToTricore(0xBB);

    /* Port configuration P33.1 */
    {
    	IfxScrPort_enablePortPad(PORT0, PIN1);//Enable SCR_P0.0 (P33.0) portpad
    	IfxScrPort_configurePortControl(PORT0, PIN1, IfxScrPort_IoControl_output_pushpullGpio);//Configure SCR_P0.0 (P33.0)
    }

	//Enable RTC module
    {
		IfxScrScu_enableModule(IfxScrScu_Module_rtc);
		//Enable RTC Interrupt
		IfxScrCpuIrq_enableInterruptNode(IfxScrCpuIrq_InterruptNode_rtc);

		//Configure RTC
		Rtc_Config.clockSource = IfxScrRtc_ClockSel_pclk;//IfxScrRtc_ClockSel_70Khz;
		Rtc_Config.bypassPrescaler = 0x1;
		Rtc_Config.enableInterruptOnCompare = 0x1;
		Rtc_Config.initialCountValue = 0x00000000;
		Rtc_Config.compareValue = 0x114E20;
		IfxScrRtc_initModule(&Rtc_Config);
		//Start RTC
		IfxScrRtc_enableRtc();
    }

    while(1)
    {
    	// Toggle Pin
    	IfxScrCpuIrq_sendMessageToTricore(i++);
    }

}
