/**
 * \file Cpu0_Main.c
 * \brief Main function definition for Cpu core 0 .
 *
 * \copyright Copyright (c) 2018 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

#include "Ifx_Types.h"
#include "Cpu/Std/IfxCpu.h"
#include "IfxPort_reg.h"
#include "IfxPms_reg.h"
#include "Pms/Std/IfxPmsPm.h"
extern const unsigned int scrProgramSize;
extern const unsigned char scrProgram[];

volatile uint32 counter0=0U;


void core0_main (void)
{
    uint32 *addrPtr;
    /*
     * !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdog in the demo if it is required and also service the watchdog periodically
     * */
	IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
	IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());

    IfxCpu_enableInterrupts();

	// Assigning Port to SCR
    {
		P32_PCSRSEL.U=0x000000F4;
		P33_PCSRSEL.U=0x0000FFFE;
		P34_PCSRSEL.U=0x0000003E;
    }

    /* SCR initialization */
    {
		addrPtr = PMS_XRAM;
		/* clear xram memory */
		while((uint32)addrPtr <= (uint32)0xF0247FFF)
		{
			*addrPtr = 0u;
			addrPtr++;
		}

		// SCR initialization
		IfxPmsPm_MemoryConfig memCfg = {&scrProgram, PMS_XRAM, scrProgramSize};
		IfxPmsPm_initScr(IfxPmsPm_ScrBootMode_userMode, FALSE, &memCfg);
		IfxPmsPm_resetScr(&MODULE_PMS);
    }

    /* Handshake between SCR and Tricore */
    IfxPmsPm_sendMessageToScr(&MODULE_PMS, 0xAA);  /* Send AA to Tricore */

    /* Wait until 0xBB is received from SCR */
    while(0xBB != IfxPmsPm_readMessageFromScr(&MODULE_PMS));

    while (1)
    {
    	counter0++;
    }
}

#if defined(__HIGHTEC__) && defined(__clang__)
void _exit(int a)
{
	while(1);
} 
#endif