/**
 * \file Cpu3_Main.c
 * \brief Main function definition for Cpu core 3 .
 *
 * \copyright Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxStm.h"
#include "IfxWtu.h"
#include "Ifx_Cfg_Ssw.h"

volatile uint32 counter3=0U;
volatile uint32 counterint3=0U;

#if !defined(IFX_CFG_SSW_RETURN_FROM_MAIN)
void core3_main (void)
{
#else
int core3_main (void)
{
#endif

    /*
     * !!WATCHDOG3 IS DISABLED HERE!!
     * Enable the watchdog in the demo if it is required and also service the watchdog periodically
     * */
	IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());

	/* Enable interrupts by setting the IE bit */
	IfxCpu_enableInterrupts();

	/* STM configuration handler */
	IfxStm_CompareConfig stmCompareConfig;

	/* Call the constructor of configuration
	 * Step 1 : Load the default configuration
	 * Step 2 : Modify the configuration parameters
	 * Step 3 : Initialize the STM with the configuration
	 * In the default configuration STM, Comparator0 is used
	 */
	IfxStm_initCompareConfig(&stmCompareConfig);
	stmCompareConfig.ticks	         = (uint32)(IFX_CFG_INTERRUPT_INTERVAL * IFX_STM_RESOULTION);
	stmCompareConfig.triggerPriority = IFX_CFG_CPU3_PRIO;
	stmCompareConfig.typeOfService   = IfxSrc_Tos_cpu3;
	/* When Virtulization is disabled SRC.VM needs to be always configured with zero */
	stmCompareConfig.vmId		     = IfxSrc_VmId_0;

	/* Initialize STM compare functionality */
	IfxStm_initCompare(&MODULE_CPU3, &stmCompareConfig);

#if !defined(IFX_CFG_SSW_RETURN_FROM_MAIN)
    while (1)
    {
    	counter3++;
    }
#else
	return 0;
#endif

}

IFX_INTERRUPT(cpu3_isr,3,IFX_CFG_CPU3_PRIO)
{
	uint32 stmTicks;
	stmTicks = (uint32)(IFX_CFG_INTERRUPT_INTERVAL * IFX_STM_RESOULTION);
    IfxStm_updateCompare(&MODULE_CPU3, IfxStm_Comparator_0, (uint32)IfxStm_get(&MODULE_CPU3) + stmTicks);
	counterint3++;
}
