/**
 * \file Ifx_Cfg.h
 * \brief Project configuration file.
 *
 * \copyright Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef IFX_CFG_H
#define IFX_CFG_H 1
/******************************************************************************/

/*______________________________________________________________________________
** Configuration for IfxClock_cfg.h
**____________________________________________________________________________*/
#define IFX_CFG_CLOCK_XTAL_FREQUENCY		(25000000)	/**< default supported: 40000000, 25000000, 20000000, 16000000 */
#define IFX_CFG_CLOCK_SYSPLL_FREQUENCY		(500000000) /**< default supported: 300000000, 200000000, 160000000, 133000000, 80000000 */
#define IFX_CFG_CLOCK_PPUPLL_FREQUENCY		(450000000) /**< default supported: If SYSPLL = 400MHz  PPUPLL = 400MHz, If SYSPLL = 500MHz  PPUPLL = 450MHz*/
#define IFX_CFG_CLOCK_PERPLL1_FREQUENCY		(160000000) /**< default supported: 320000000, 160000000 */
#define IFX_CFG_CLOCK_PERPLL2_FREQUENCY		(200000000) /**< default supported: 200000000 */
#define IFX_CFG_CLOCK_PERPLL3_FREQUENCY		(200000000) /**< default supported: 200000000 */

/*______________________________________________________________________________
** Configuration for Software managed interrupt
**____________________________________________________________________________*/

// #define IFX_PROT_ENABLED 1
//#define IFX_USE_SW_MANAGED_INT

#define IFX_STM_RESOULTION IFX_CFG_CLOCK_SYSPLL_FREQUENCY

#define IFX_CFG_INTERRUPT_INTERVAL (0.003)

#define IFX_CFG_CPU0_PRIO 10
#define IFX_CFG_CPU1_PRIO 10
#define IFX_CFG_CPU2_PRIO 10
#define IFX_CFG_CPU3_PRIO 10
#define IFX_CFG_CPU4_PRIO 10
#define IFX_CFG_CPU5_PRIO 10

//#define IFX_CFG_EXTEND_TRAP_HOOKS

/******************************************************************************/

//#define IFX_VP_DEBUG_PRINT   1u

#define DEVICE_TC4DX			1


#if defined(__CARC__) || defined (__arc__)
#define IFX_PPU_BUILD
#else
#undef IFX_PPU_BUILD
#endif

/******************************************************************************/

#endif /* IFX_CFG_H */
