/**
 * \file IfxMailBox.h
 *
 * \version TBD
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef COMMON_MBX_H_
#define COMMON_MBX_H_

/** \brief LOCK
 */
#define RESOURCE_LOCK              (0xB0580E00)

/** \brief TC0 Mailbox
 */
#define TRICORE_0_REQUEST_MAILBOX  (0xB0580200)

/** \brief TC1 Mailbox
 */
#define TRICORE_1_REQUEST_MAILBOX  (0xB0580400)

/** \brief TC2 Mailbox
 */
#define TRICORE_2_REQUEST_MAILBOX  (0xB0580600)

/** \brief TC3 Mailbox
 */
#define TRICORE_3_REQUEST_MAILBOX  (0xB0580800)

/** \brief TC4 Mailbox
 */
#define TRICORE_4_REQUEST_MAILBOX  (0xB0580A00)

/** \brief TC5 Mailbox
 */
#define TRICORE_5_REQUEST_MAILBOX  (0xB0580C00)

/** \brief TC5 Mailbox
 */
#define TRICORE_6_HANDSHAKE_MAILBOX  (0xB0581000)

/** \brief MAX Args
 */
#define MAX_ARGS (10)

/** \brief Num of Cores
 */
#define MAX_NUM_CORES 6U

/** \brief if defined, the interrupt from Server to Client is configured as the notifier
 */
//#define S2C_INTERRUPT_NOTIFICATION 1

/** \brief Status of the operation/service
 */
typedef enum
{
	IfxMailbox_Status_requestDone=0U,      /**< \brief Service Request Done */
	IfxMailbox_Status_requestInProgress,   /**< \brief Service Request In progress */
	IfxMailbox_Status_successful,          /**< \brief Service Request executed successfully */
	IfxMailbox_Status_notsuccessful,       /**< \brief Service Request not executed successfully */
	IfxMailbox_Status_tryLater             /**< \brief Server busy/ occupied */
}IfxMailbox_Status;

/** \brief New command or not
 */
typedef enum
{
	IfxMailbox_Command_none=0U,    /**< \brief No new command */
	IfxMailbox_Command_new         /**< \brief New command */
}IfxMailbox_Command;

/** \brief Mailbox structure
 */
typedef struct
{
	unsigned int command;     /**< \brief Describe if there is a new command */
	unsigned int status;      /**< \brief Describe the status of the request */
	unsigned int id;          /**< \brief Identifier to the specific service request */
	unsigned int numArgs;     /**< \brief  Number of Data to be passed to the Server */
	int *args[MAX_ARGS];      /**< \brief Pointer to the data members */
}IfxMailbox;

#endif /* COMMON_MBX_H_ */
