/**
 * \file IfxLmu.c
 * \brief This file contains the APIs for Trap related functions.
 *
 *
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 */


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "IfxLmu.h"
#include "IfxApApu.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void IfxLmu_configProtection(const IfxLmu_ProtectionConfig *config)
{
    int region;
    for(region= 0; region <= config->numRegions; region++)
    {
        IfxApApu_ApuConfig apuConfig=
        {
            .wraTagId= (uint32)config->regions[region].wMasters.enableTagBits,
            .wrbTagId= (uint32)(config->regions[region].wMasters.enableTagBits >> 32),
            .rdaTagId= (uint32)config->regions[region].rMasters.enableTagBits,
            .rdbTagId= (uint32)(config->regions[region].rMasters.enableTagBits >> 32),
            .vmWrId= config->regions[region].wMasters.enableVmBits,
            .vmRdId= config->regions[region].rMasters.enableVmBits,
            .prsWrId= config->regions[region].wMasters.enablePrsBits,
            .prsRdId= config->regions[region].rMasters.enablePrsBits
        };

        IfxApApu_ApuMemoryConfig memConfig=
        {
            .apuConfig= &apuConfig,
            .rgnlaVal= (uint32)config->regions[region].startAddress & 0xDFFFFFC0U,
            .rgnuaVal= (uint32)config->regions[region].endAddress & 0xDFFFFFC0U
        };

        IfxApApu_configMemoryAccess((Ifx_ACCEN_ACCEN *)&config->module->ACCENCFG, &memConfig, (Ifx_PROT_PROT *)&config->module->PROTRGN, (uint8)region);
    }
}

