/**
 * \file SharedData.h
 * \brief This file contains the APIs for Trap related functions.
 *
 *
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 */

#ifndef SHAREDDATA_H_
#define SHAREDDATA_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Cfg.h"
#include "Ifx_Types.h"
#include "Compilers.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ppuInterfaceData (*((SharedData_PpuIfConstants *)__PPU_IF_CONSTANTS))

/*********************************************************************************************************************/
/*----------------------------------------------------Data Types-----------------------------------------------------*/
/*********************************************************************************************************************/
/* PPU SPECIFIC DATA TYPES */

/** \brief Copy-table data of PPU vectors for TriCore to Copy to CSM memory.
 * Such a is located at known fixed address together with other shared pointers
 */
typedef struct
{
    void *const    sourceAddress;
    void *const    destinationAddress;
    const uint32   size;
} SharedData_PpuCopyTable;

/** \brief Shared IPC data produced at PPU application
 * This structure is always located at RAM and updated during runtime.
 * Such data could also be pointers to other structures.
 * The members' position could also be altered based on project need.
 * Each members need to be initialized by PPU during its init process.
 * Update the API: PpuInterface_initSharedData(PpuInterface_PpuSharedData);
 *
 */

/* Forward declaration of the IPC struct */
typedef struct TcPpuIpcData TcPpuIpcData;


/** \brief PPU Interface Constants
 * All the shared pointers that are between TriCore and PPU are listed as below
 * structure members. Please note that, the position of such data is fixed by the
 * linker command file of PPU project.
 */
typedef struct
{
    /* !!! Don't alter the position of structure members !!! */
	SharedData_PpuCopyTable  ppuCopyTable;     /**< \brief PPU Copy-table for TriCore*/
	TcPpuIpcData *const      ppuIpcDataPtr;    /**< \brief Data pointer for PPU IPC */
} SharedData_PpuIfConstants;


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/


/*-------------------------------------------------------------------------------------------------------------------*/
/** \brief Exported pointers from PPU linker file.
 */
//extern unsigned int __PPU_IF_CONSTANTS[];                              /* FIxed memory location at NVM of PPU application*/
extern SharedData_PpuIfConstants __PPU_IF_CONSTANTS[]; // this location (pointer) will be filled by linker, which knows the address


#endif /* SHAREDDATA_H_ */
