/**
 * \file PpuInterface.c
 * \brief This file contains the APIs for Trap related functions.
 *
 *
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 */


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Cfg.h"
#include "PpuInterface.h"
#include "SharedData.h"
#include "IfxPpucCore.h"
#include "IfxSrc.h"


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern unsigned __PPU_CSM_START[];
extern unsigned __PPU_CSM_END[];
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void PpuInterface_startPpu(void)
{
    /* Drive the Initial Program counter value on PPU's PC interface and
     * release it from the state of reset. The PPU starts execution upon
     * release of reset.
     */

    IfxPpucCore_enableModule(&MODULE_PPU);

    /* Wait untill the module is enabled */
    while(IfxPpucCore_isModuleEnabled(&MODULE_PPU) != TRUE);

    {
        /* Clear and ECC-Initialize the CSM */
        //TODO:  This is a workaround because of VMT driver not supporting 3rd Party IPs
        volatile uint64*addressCSM = (volatile uint64*)__PPU_CSM_START;
        while (addressCSM < (volatile uint64*)__PPU_CSM_END) *addressCSM++= 0x0ULL;
    }

    {
        volatile uint32* vectorTableSource = (uint32*)ppuInterfaceData.ppuCopyTable.sourceAddress;
        volatile uint32* vectorTableDest = (uint32*)ppuInterfaceData.ppuCopyTable.destinationAddress;
        /* Copy vector table of PPU to start of CSM
         * Start of CSM is the default address for the reset vector
         * Changing the default reset vector address requires a PPU kernel rest
         * and has impact on the on the debugging */
        while((void *)vectorTableSource < (void *)((uint32)ppuInterfaceData.ppuCopyTable.sourceAddress + ppuInterfaceData.ppuCopyTable.size))
        {
            *vectorTableDest++ = *vectorTableSource++;
        }
    }

    {
        /* Enable SRNs for PPU */
        IfxSrc_init(&MODULE_SRC.PPU.ICI, IfxSrc_Tos_ppu, (Ifx_Priority)0, (IfxSrc_VmId)0);
    }

    IfxPpucCore_startCore(&MODULE_PPU);
    //IfxPpucCore_configureCoreAndRun(&MODULE_PPUC, (uint32)__PPU_CSM_START);

    /* Wait until PPU has booted up */
    while(PpuInterface_isPpuBootedUp() == FALSE);
}

