/**
 * \file PpuInterface.h
 * \brief This file contains the APIs for Trap related functions.
 *
 *
 * \copyright Copyright (c) 2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *
 */

#ifndef PPUINTERFACE_H_
#define PPUINTERFACE_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Cfg.h"
#include "IfxSrc.h"


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*----------------------------------------------------Data Types-----------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void PpuInterface_startPpu(void);                                                     /* Configure and Start the PPU */

/** \brief API to signal that PPU bootup is done.
 * This is done by triggering the PPUC Inter core communication interrupt up.
 * If one of the TriCores are configured to receive the interrupt (or poll),
 * then such communication is established.
 */
IFX_INLINE boolean PpuInterface_acknowledgePpuSignal(void)
{
    boolean requested= IfxSrc_isRequested(&MODULE_SRC.GPSR[0].SR0);
    if(requested)
    {
        IfxSrc_clearRequest(&MODULE_SRC.GPSR[0].SR0);
    }
    return requested;
}

/** \brief API to acknowledge that PPU boot-up is done.
 *
 */
IFX_INLINE boolean PpuInterface_isPpuBootedUp(void)
{
    return PpuInterface_acknowledgePpuSignal();
}

/** \brief API to synchronize with PPU.
 * This is done by triggering the PPUC Inter-core communication interrupt.
 * PPU is configured to receive the interrupt (or poll), then such communication is established.
 */
IFX_INLINE void PpuInterface_signalToPpu(void)
{
    /* Wait until PPU takes up last signal */
    while(IfxSrc_isRequested(&MODULE_SRC.PPU.ICI));
    IfxSrc_setRequest(&MODULE_SRC.PPU.ICI);
}

#endif /* PPUINTERFACE_H_ */
